/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ComplianceCertificate {
  export type CertificateStruct = {
    id: BigNumberish;
    timestamp: BigNumberish;
    hash: BytesLike;
    submitter: AddressLike;
    co2: BigNumberish;
    pm25: BigNumberish;
    so2: BigNumberish;
    noise: BigNumberish;
  };

  export type CertificateStructOutput = [
    id: bigint,
    timestamp: bigint,
    hash: string,
    submitter: string,
    co2: bigint,
    pm25: bigint,
    so2: bigint,
    noise: bigint
  ] & {
    id: bigint;
    timestamp: bigint;
    hash: string;
    submitter: string;
    co2: bigint;
    pm25: bigint;
    so2: bigint;
    noise: bigint;
  };
}

export interface ComplianceCertificateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificateCount"
      | "getCertificate"
      | "getCertificateIdsBy"
      | "owner"
      | "setThresholds"
      | "submitReading"
      | "thresholdCO2"
      | "thresholdNoise"
      | "thresholdPM25"
      | "thresholdSO2"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateIssued"): EventFragment;

  encodeFunctionData(
    functionFragment: "certificateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateIdsBy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReading",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdCO2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdNoise",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdPM25",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdSO2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateIdsBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdCO2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdNoise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdPM25",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdSO2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    id: BigNumberish,
    submitter: AddressLike,
    timestamp: BigNumberish,
    hash: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    submitter: string,
    timestamp: bigint,
    hash: string
  ];
  export interface OutputObject {
    id: bigint;
    submitter: string;
    timestamp: bigint;
    hash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceCertificate extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceCertificate;
  waitForDeployment(): Promise<this>;

  interface: ComplianceCertificateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificateCount: TypedContractMethod<[], [bigint], "view">;

  getCertificate: TypedContractMethod<
    [id: BigNumberish],
    [ComplianceCertificate.CertificateStructOutput],
    "view"
  >;

  getCertificateIdsBy: TypedContractMethod<
    [submitter: AddressLike],
    [bigint[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setThresholds: TypedContractMethod<
    [
      co2: BigNumberish,
      pm25: BigNumberish,
      so2: BigNumberish,
      noise: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitReading: TypedContractMethod<
    [
      co2: BigNumberish,
      pm25: BigNumberish,
      so2: BigNumberish,
      noise: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  thresholdCO2: TypedContractMethod<[], [bigint], "view">;

  thresholdNoise: TypedContractMethod<[], [bigint], "view">;

  thresholdPM25: TypedContractMethod<[], [bigint], "view">;

  thresholdSO2: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ComplianceCertificate.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificateIdsBy"
  ): TypedContractMethod<[submitter: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [
      co2: BigNumberish,
      pm25: BigNumberish,
      so2: BigNumberish,
      noise: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitReading"
  ): TypedContractMethod<
    [
      co2: BigNumberish,
      pm25: BigNumberish,
      so2: BigNumberish,
      noise: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "thresholdCO2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "thresholdNoise"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "thresholdPM25"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "thresholdSO2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(uint256,address,uint256,bytes32)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
  };
}
